sudo: false
cache: bundler
language: ruby
rvm:
  - 2.4.2
before_install: gem install bundler -v 1.16.1

jobs:
  include:
    - stage: analyze
      script: bundle exec rubocop
    - stage: test
      script: bundle exec rspec
